baseURL = 'https://2635764856.github.io/'
languageCode = 'zh-cn'
title = 'Terminal root@domain'
theme = 'terminal'
paginate = 5

[params]
  # 基础设置
  themeColor = 'green'
  fullWidthTheme = true
  showConsoleWindow = true
  
  # 首页打字机与简介设置
  showTerminalTitle = true
  TerminalPrefix = 'root@hacker-space:~#'
  TerminalTitle = 'System Initialized.'
  TerminalDescription = '''
  > [INFO] Accessing user profile...
  > Hello, World! I am **2635764856**.
  > A passionate Software Engineer & Open Source Enthusiast.
  > Welcome to my terminal space.
  '''

  # Logo 设置
  logoText = '~/home/blog'
  logoHomeLink = '/'

# 菜单设置
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "📂 文章列表"
    url = "/posts"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "👨‍💻 关于我"
    url = "/about"
    weight = 2
  [[menu.main]]
    identifier = "github"
    name = "🐙 GitHub"
    url = "https://github.com/2635764856"
    weight = 3
  [[menu.main]]
    identifier = "tags"
    name = "🏷️ 标签云"
    url = "/tags"
    weight = 4